version: '3.7'
services:
  app:
    build: 
      context: .
      dockerfile: ./_docker/app/Dockerfile
    env_file:
      - ./_docker/app/.env
    volumes:
      - ./app:/go/src/app
      - ./log/:/var/log/app
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: ./_docker/db/Dockerfile
    env_file:
      - ./_docker/db/.env
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306